spring:
  config:
    imoprt: "optional:classpath:.env[.properties]"
  application:
    name: portfolio-api
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/portfolio_db
    username: ${PM_DB_USERNAME}
    password: ${PM_DB_PASSWORD}
    audit:
      jdbcUrl: jdbc:mysql://localhost:3307/audit_db
      username: ${AUDIT_DB_USERNAME}
      password: ${AUDIT_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false # open-in-view disabled for multi-datasource compliance.
  security:
    user:
      name: ${SPRING_SECURITY_USERNAME}
      password: ${SPRING_SECURITY_PASSWORD}

server:
  port: 8080

logging:
  file:
    name: application/log/application.log
  level:
    org.springframework.security: DEBUG # INFO