spring:
  application:
    name: portfolio-api
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/portfolio_db
    username: root
    password: ${DB_PASSWORD}
    audit:
      jdbcUrl: jdbc:mysql://localhost:3307/audit_db
      username: root
      password: ${DB_AUDIT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false # open-in-view disabled for multi-datasource compliance.
  security:
    user:
      name: root
      password: root

server:
  port: 8080

logging:
  file:
    name: application/log/application.log
  level:
    org.springframework.security: DEBUG # INFO